"""
Email Notification Service.
Sends daily digest emails and watchlist alerts.
"""

import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List
from datetime import datetime

from sqlalchemy.orm import Session

from app.config import settings
from app.models.listing import Listing
from app.models.analysis import Analysis

logger = logging.getLogger(__name__)


def send_daily_digest(db: Session):
    """Send a daily email digest with top property opportunities."""
    if not settings.smtp_username or not settings.email_to:
        logger.warning("Email not configured - skipping daily digest")
        return

    # Get top deals
    results = (
        db.query(Listing, Analysis)
        .join(Analysis)
        .filter(Analysis.verdict.in_(["STRONG_BUY", "BUY"]))
        .order_by(Analysis.composite_score.desc())
        .limit(10)
        .all()
    )

    if not results:
        logger.info("No top deals to report - skipping digest email")
        return

    # Build email
    subject = f"NZ Property Finder - {len(results)} Opportunities ({datetime.now().strftime('%d %b %Y')})"
    body = _build_digest_html(results)

    _send_email(subject, body)
    logger.info(f"Daily digest sent with {len(results)} properties")


def send_watchlist_alert(watchlist_name: str, listings: List[Listing]):
    """Send an alert for new listings matching a watchlist item."""
    if not settings.smtp_username or not settings.email_to:
        return

    subject = f"NZ Property Finder Alert: {len(listings)} new matches for '{watchlist_name}'"
    body = _build_alert_html(watchlist_name, listings)

    _send_email(subject, body)
    logger.info(f"Watchlist alert sent for '{watchlist_name}' with {len(listings)} matches")


def _build_digest_html(results: list) -> str:
    """Build HTML email body for daily digest."""
    html = """
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #1a5276;">NZ Property Finder - Daily Digest</h1>
    <p style="color: #666;">Top investment opportunities found today:</p>
    <hr>
    """

    for i, (listing, analysis) in enumerate(results, 1):
        strategy = analysis.strategy_decision or {}
        flip = analysis.flip_financials or {}
        rental = analysis.rental_financials or {}

        verdict_color = {
            "STRONG_BUY": "#27ae60",
            "BUY": "#2ecc71",
            "MAYBE": "#f39c12",
            "PASS": "#e74c3c",
        }.get(analysis.verdict, "#95a5a6")

        html += f"""
        <div style="border: 1px solid #ddd; border-radius: 8px; padding: 16px; margin: 12px 0;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <h3 style="margin: 0;">#{i}: {listing.full_address or listing.address}</h3>
                <span style="background: {verdict_color}; color: white; padding: 4px 12px;
                       border-radius: 4px; font-weight: bold;">
                    Score: {analysis.composite_score:.0f} | {analysis.verdict}
                </span>
            </div>
            <p style="color: #666; margin: 8px 0;">{listing.display_price} | {listing.bedrooms or '?'}br | {listing.suburb}</p>
            <p><strong>Strategy:</strong> {strategy.get('recommended_strategy', 'N/A')}</p>
            <p><strong>Flip ROI:</strong> {flip.get('roi_percentage', 0):.1f}% |
               <strong>Rental Yield:</strong> {rental.get('gross_yield_percentage', 0):.1f}%</p>
            <a href="{listing.property_url}" style="color: #2980b9;">View on TradeMe</a>
        </div>
        """

    html += """
    <hr>
    <p style="color: #999; font-size: 12px;">
        Generated by NZ Property Finder. View full details on your dashboard.
    </p>
    </body></html>
    """

    return html


def _build_alert_html(watchlist_name: str, listings: List[Listing]) -> str:
    """Build HTML email body for watchlist alerts."""
    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
    <h1 style="color: #1a5276;">Watchlist Alert: {watchlist_name}</h1>
    <p>{len(listings)} new listings match your saved search criteria:</p>
    <hr>
    """

    for listing in listings[:10]:
        html += f"""
        <div style="border: 1px solid #ddd; border-radius: 8px; padding: 12px; margin: 8px 0;">
            <h3 style="margin: 0;">{listing.full_address or listing.address}</h3>
            <p>{listing.display_price} | {listing.bedrooms or '?'}br | {listing.suburb}</p>
            <a href="{listing.property_url}">View on TradeMe</a>
        </div>
        """

    html += "</body></html>"
    return html


def _send_email(subject: str, html_body: str):
    """Send an HTML email via SMTP."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.email_from or settings.smtp_username
        msg["To"] = settings.email_to

        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_username, settings.smtp_password)
            server.send_message(msg)

        logger.info(f"Email sent: {subject}")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
